name: Lighthouse Report

on:
  push:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Lighthouse
        run: |
          npm install -g @lhci/cli
          lhci autorun --collect.staticDistDir=.
          # どこに何があるか見せてもらう
          ls -R .lighthouseci/ || echo "ディレクトリが見つかりません"
          
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci/*
